theme: cayman
title: Akhil Theerthala
description: Senior Data Scientist | AI Research | Financial ML | Open Source Contributor
url: "https://akhil-theerthala.github.io"
author:
  name: Akhil Theerthala
  email: akhiltvsn@gmail.com
  github: akhil-theerthala
  linkedin: akhil-theerthala
  medium: akhiltvsn
  huggingface: akhil-theerthala
