remote_theme: pages-themes/cayman@v0.2.0
title: Akhil Theerthala
description: Senior Data Scientist | AI Research | Financial ML | Open Source Contributor
url: "https://akhil-theerthala.github.io"
plugins:
  - jekyll-remote-theme
author:
  name: Akhil Theerthala
  email: akhiltvsn@gmail.com
  github: akhil-theerthala
  linkedin: akhil-theerthala
  medium: akhiltvsn
  huggingface: akhil-theerthala
